version: '2'

services:
  db:
    build: "./docker/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  php:
    build: ./docker/php
    ports:
      - 80:80
    links:
      - db
    volumes:
      - "./web:/var/www/html"
  pma:
    image: "phpmyadmin/phpmyadmin"
    links:
      - db
    ports:
      - "8080:80"
